### ISSUE TITLE
Create component for input fields of Login/Register pages

### ISSUE THREAD

**Issue by tresimovic** [chrisj117/CS-472-GROUP-2-PROJECT#119]
**Is your feature request related to a problem? Please describe.**
 - Make Login/Register page more compact and concise by implementing a component to be reused to create the input fields on those pages.

**Describe the solution you'd like**
- Create a JSX component that utilizes props. This will replace the hard-coded individual input fields on those two pages.

**Describe alternatives you've considered**
- N/A

**Additional context**
- N/A

**Comment by danielogen** [comment]
Nice refactoring done by @tresimovic
