### ISSUE TITLE
Register Page Mobile Responsiveness

### ISSUE THREAD

**Issue by chrisj117** [chrisj117/CS-472-GROUP-2-PROJECT#127]
**Is your feature request related to a problem? Please describe.**
- The Register page is not mobile responsive

**Describe the solution you'd like**
- Allow the Register page to fit on all screens
- Test this using inspect element
- Use media query styles in TailwindCSS
- Since this page and the Login page share similar fields, apply the same scaling, styles, etc. to the Login page

**Describe alternatives you've considered**
- N/A

**Additional context**
- Quick references: https://tailwindcss.com/docs/responsive-design and https://tailwindcss.com/docs/font-size

**Comment by Ruaaann** [comment]
Branch related to issue has been merged.
