### ISSUE TITLE
CI pipeline for frontend

### ISSUE THREAD

**Issue by danielogen** [chrisj117/CS-472-GROUP-2-PROJECT#14]
**Is your feature request related to a problem? Please describe.**
-  There is no CI pipeline for frontend development

**Describe the solution you'd like**
- Configure CI pipeline for code linting, running unit test and coverage, etc.

**Describe alternatives you've considered**
- N/A

**Additional context**
- N/A

**Comment by azboss2021** [comment]
I believe @AB27-source has plans to complete this if you would like to assign the task to him. If not, someone else can pick this issue up.
