### ISSUE TITLE
Creation of Endpoint to Retrieve Course Information

### ISSUE THREAD

**Issue by angadb27** [chrisj117/CS-472-GROUP-2-PROJECT#149]
**Is your feature request related to a problem? Please describe.**
- There is a need for an endpoint that allows users to retrieve detailed information about specific courses offered by a school. This endpoint should facilitate easy access to course data using a combination of school identifier and course details.

**Describe the solution you'd like**
- The implementation of a new RESTful API endpoint following the format: `{base_url}/courses/{school_short_name}/{course_subject_catalog}`. This endpoint should:
  - Enable users to GET detailed information for a specific course.
  - Use the school's short name and the combination of the `course's subject` and `catalog number` to uniquely identify and fetch course details.

**Describe alternatives you've considered**
- N/A 

**Additional context**
- **Endpoint Structure**: GET `{base_url}/courses/{school_short_name}/{course_subject_catalog}`
- **Parameters**:
  1. `school_short_name`: A concise identifier for the school.
  2. `course_subject_catalog`: A combination of the `course subject` and `catalog number` to uniquely identify the course.
- **Expected Response**: The endpoint should return the following information `school`,  `subject`, `catalog_number`, `title`, `professors`

**Comment by danielogen** [comment]
Thanks @angadb27 , This looks good. It covers everything!
