### ISSUE TITLE
CI for backend API

### ISSUE THREAD

**Issue by danielogen** [chrisj117/CS-472-GROUP-2-PROJECT#15]
**Is your feature request related to a problem? Please describe.**
-  There is no CI pipeline for backend API

**Describe the solution you'd like**
- Configure CI pipeline for code linting, running unit test and coverage, etc.

**Describe alternatives you've considered**
- N/A

**Additional context**
- N/A

**Comment by azboss2021** [comment]
For the code linting, we should use ESlint for the Javascript, and Flake8 for the Python.

**Comment by danielogen** [comment]
> For the code linting, we should use ESlint for the Javascript, and Flake8 for the Python.

Yes, looks ESlint is the preferred choice among JavaScript developer. For Python, we have `PyLint` and `Flake8`, I think we can just go with `Flake8`.
