### ISSUE TITLE
Create Home Page

### ISSUE THREAD

**Issue by azboss2021** [chrisj117/CS-472-GROUP-2-PROJECT#20]
**Is your feature request related to a problem? Please describe.**

- There is no home page

**Describe the solution you'd like**

- Follow an agreed-upon design and create it using React Bootstrap

**Describe alternatives you've considered**

- N/A

**Additional context**

- N/A

**Comment by chrisj117** [comment]
I could attempt solving this issue. For clarity, are we now using TailwindCSS and trying to emulate the screenshot below (from Design Doc 1)? Also, should we develop this home page on its own branch or on the `pages-and-routing` branch?

![image](https://github.com/chrisj117/CS-472-GROUP-2-PROJECT/assets/35480893/faafaff8-f897-41d1-b184-260c0dae6216)

**Comment by chrisj117** [comment]
I'll be creating a new branch specifically for the home page and loosely following the Design Doc 1 prototype with TailwindCSS 👍
