### ISSUE TITLE
Scrape UNLV Course Catalog To Use In Models

### ISSUE THREAD

**Issue by Ruaaann** [chrisj117/CS-472-GROUP-2-PROJECT#22]
Is your feature request related to a problem? Please describe.

- Preliminary data is necessary in order to enable front end development, and build a prototype.

Describe the solution you'd like

- Scrape [https://www.unlv.edu/online/courses](https://www.unlv.edu/online/courses) and create a csv file of all unique subjects, catalog numbers, and titles. This csv then must be injested into a Django model.

Describe alternatives you've considered

- CSV is likely the best course of action to then injest into Django models, but open to alternatives.

Additional context

- N/A

**Comment by azboss2021** [comment]
This is a good issue that should be done soon so we can get started with the database 👍
