### ISSUE TITLE
Request School Endpoint: Setup model and serializer 

### ISSUE THREAD

**Issue by danielogen** [chrisj117/CS-472-GROUP-2-PROJECT#39]
**Is your feature request related to a problem? Please describe.**
- This feature is required to allow users to make request for a new school to be added to the our platform

**Describe the solution you'd like**
- Create a new model and serializer for handling new school request 

**Describe alternatives you've considered**
- N/A

**Additional context**
- N/A

**Comment by danielogen** [comment]
What could be some for the information a user need to provide when making  a request for new school to add to the platform? @azboss2021 , @angadb27 .

I guess they could provide: name and website?

**Comment by Ruaaann** [comment]
Branch that dealt with this was merged!
