### ISSUE TITLE
School Search Box

### ISSUE THREAD

**Issue by azboss2021** [chrisj117/CS-472-GROUP-2-PROJECT#4]
The School Search Box will allow the user to enter in keywords and filter the search results by what the search algorithm determines are the most appropriate results. These results will be the schools that have been previously added by admins. This can be supported by libraries or programmed from scratch.

**Comment by azboss2021** [comment]
This will be on the home page.

**Comment by LLinlll** [comment]
@danielogen Hi,I'm interested in this task. Can you assign it to me?
