### ISSUE TITLE
Request School Endpoint: Create POST endpoint and write unitest

### ISSUE THREAD

**Issue by danielogen** [chrisj117/CS-472-GROUP-2-PROJECT#40]
**Is your feature request related to a problem? Please describe.**
- User want to post request for a new school to be added 

**Describe the solution you'd like**
- Write code for POST endpoint and write unit tests

**Describe alternatives you've considered**
- N/A

**Additional context**
- Example endpoint: `POST /request-school`

**Comment by Ruaaann** [comment]
Branch that dealt with this was merged!
