### ISSUE TITLE
Request School Endpoint: Create GET endpoint and write unit test

### ISSUE THREAD

**Issue by danielogen** [chrisj117/CS-472-GROUP-2-PROJECT#41]
**Is your feature request related to a problem? Please describe.**
- The frontend need to get all the request submitted by users 

**Describe the solution you'd like**
- Write the GET endpoint and unit test for retrieving all requests submitted by the user 

**Describe alternatives you've considered**
- N/A

**Additional context**
- `GET: /request-school`

**Comment by Ruaaann** [comment]
Branch that dealt with this was merged!
