### ISSUE TITLE
Request School Endpoint: Write DELETE endpoint and unit test

### ISSUE THREAD

**Issue by danielogen** [chrisj117/CS-472-GROUP-2-PROJECT#42]
**Is your feature request related to a problem? Please describe.**
- The frontend need to delete the request submitted by users 

**Describe the solution you'd like**
- Write the DELETE endpoint and unit test for deleting a requests submitted by the user. 
- Return appropriate status code, in this case `204 NOT CONTENT`.

**Describe alternatives you've considered**
- N/A

**Additional context**
- `DELETE: /request-school/{request_id}`

**Comment by Ruaaann** [comment]
Branch that dealt with this was merged!
