### ISSUE TITLE
Load UNLV Course Data into Database

### ISSUE THREAD

**Issue by Ruaaann** [chrisj117/CS-472-GROUP-2-PROJECT#84]
**Is your feature request related to a problem? Please describe.**
- The course data scraped earlier needs to be loaded into our backend database. This will assist front end development at this stage.

**Describe the solution you'd like**
- Create a solution to load the unlv courses csv into the course database (for UNLV).

**Describe alternatives you've considered**
- N/A

**Additional Context**
- This loading of courses will have to be done for more schools beyond just UNLV, so a solution that considers this generalization would be nice.

**Comment by danielogen** [comment]
This is a key issue to our project, great getting it done @Ruaaann
