### ISSUE TITLE
Create Course Model for School App

### ISSUE THREAD

**Issue by Ruaaann** [chrisj117/CS-472-GROUP-2-PROJECT#86]
**Is your feature request related to a problem? Please describe.**
- We need a model to store courses data

**Describe the solution you'd like**
- Create a Django model in the School app to hold relevant course data

**Describe alternatives you've considered**
- N/A

**Additional context**
- Related issue: #84

**Comment by danielogen** [comment]
This is a key feature for our application

**Comment by Ruaaann** [comment]
Branch pertaining to this issue has been merged.
