### ISSUE TITLE
Add light/dark mode

### ISSUE THREAD

**Issue by chrisj117** [chrisj117/CS-472-GROUP-2-PROJECT#98]
**Is your feature request related to a problem? Please describe.**
- Our toolbar's design includes a light/dark mode button, but as of now it lacks functionality

**Describe the solution you'd like**
- Seamless light/dark mode integrated utilizing TailwindCSS and React

**Describe alternatives you've considered**
- Removing the button

**Additional context**
- For quick reference, the button's current code resides in `/web/src/components/Navbar.jsx`

**Comment by danielogen** [comment]
This is a nice to have feature, I can't wait to test it

**Comment by chrisj117** [comment]
Solved by #121
